# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: pull_request
    workflow_dispatch:

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
