name: CI

permissions:
  contents: read
  pull-requests: read #add some permissions to try to get corrections running 

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Token sanity
 
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "TOKEN_PRESENT=${{ secrets.GITHUB_TOKEN != '' }}"