name: CI

permissions:
  contents: read
  pull-requests: read
  issues: write  #add some permissions to try to get corrections running 

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5 
        with:
          python-version: '3.12'
      - name: install deps
        run: python -m pip install --upgrade pip && pip install unidiff requests openai
      - name: Run critter 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python crit.py